version: "2"
services:
  app:
    hostname: game
    image: game.richardscollin.com
    build: .
    restart: unless-stopped
    networks: ["container-net"]
    environment:
      PORT: "80"
  coturn:
    hostname: coturn
    image: coturn/coturn:alpine
    network_mode: "host"
