version: "2"
services:
  app:
    hostname: game
    image: game.richardscollin.com
    build: .
    restart: unless-stopped
    networks: ["container-net"]
  coturn:
    hostname: coturn
    image: coturn.richardscollin.com
    build:
      context: .
      dockerfile: coturn.Dockerfile
    network_mode: "host"
    volumes:
      - "/etc/letsencrypt/:/etc/letsencrypt:ro"
