#!/bin/sh
# Deploy to production using git
DEPLOY_DIR=/home/collin/game-platform
GIT_WORK_TREE="${DEPLOY_DIR}" git checkout -f
cd "${DEPLOY_DIR}"
cp config.server.js config.js
yarn install --production
exit
